server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movieService
          predicates:
            - Path=/movies/**
        - id: serie-service-route
          uri: lb://serie-service
          predicates:
            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalogService
          predicates:
            - Path=/catalog/**
      default-filters:
        - OIDCTokenRelay
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: 258182736623-62s00juj38h7saast9hfnrqdv1m4bse5.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true