server:
  port: ${PORT:8083}

spring:
  application:
    name: catalogService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

resilience4j:
  circuitbreaker:
    instances:
      circuitGetCatalogByGenre:
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 15000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      circuitGetCatalogByGenre:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions[0]: feign.FeignException$InternalServerError